# Generated by Django 4.1.3 on 2023-01-02 05:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id_book', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('img', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_book',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('titre_category', models.CharField(max_length=400)),
                ('nbr_book', models.IntegerField()),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_categorie',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('Commande_price', models.FloatField()),
                ('nbr_produit', models.IntegerField()),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_commande',
            },
        ),
        migrations.CreateModel(
            name='Paiment',
            fields=[
                ('id_paiment', models.AutoField(primary_key=True, serialize=False)),
                ('some_paiment', models.FloatField()),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_paiment',
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_quantity', models.IntegerField()),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commande')),
            ],
            options={
                'db_table': 'app_lignecommande',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='books',
            field=models.ManyToManyField(through='app.LigneCommande', to='app.book'),
        ),
        migrations.AddField(
            model_name='commande',
            name='id_paiment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.paiment'),
        ),
        migrations.AddField(
            model_name='commande',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='id_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorie'),
        ),
    ]
